<div className='experience'>
    <div className="container">
        <h2>Technologies</h2>
    <div className="card-container">
    {ha}
        <div className="card">
            <ExpCard 
            icon={<TiHtml5 className='icon'
              
            />}

            />
        </div>
        <div className="card">
            <ExpCard icon={<DiCss3 className='icon'/>}/>
        </div>
        <div className="card">
            <ExpCard icon={<DiSass className='icon'/>}/>
        </div>
        <div className="card">
            <ExpCard icon={<DiResponsive className='icon'/>}/>
        </div>
        <div className="card">
            <ExpCard icon={<DiJavascript1 className='icon'/>}/>
        </div>
        <div className="card">
            <ExpCard icon={<DiNodejsSmall className='icon'/>}/>
        </div>
        <div className="card">
            <ExpCard icon={<DiReact className='icon'/>}/>
        </div>

        <div className="card">
            <ExpCard icon={<SiGimp className='icon'/>}/>
        </div>
        <div className="card">
            <ExpCard icon={<DiPhp className='icon'/>}/>
        </div>
    </div>  
    <a href="/" className='btn'>GitHub</a>  
    </div>
</div>